range1=range(20)
print(range1)
type(range1)
print("type of range1 is =",type(range1))
print(list(range1))
range2=range(2,8)
print(range2)
print(list(range2))
range3=range(3,12,3)
print(range3)
print(list(range3))
print(range1.step)
print(range3.stop)
print(range2.start)
print(range3.index(9))
print(range2.count(2))