from operator import index

a=(1,2,3,4,5,6)
print(type(a))
print("type of a is=",type(a))
Tuple1 = (1, 2, 3, 4, 5)
Tuple2 = ("apple", "banana", "cherry")
Tuple3 = (True, False, True)
Tuple4 = ("apple", 1, True)
Tuple5 = (1, 2, 3, 4, 5)
Tuple6 = (1, 2, "apple", 4, 5)
Tuple7 = ("apple", 1, True, 2, 3)
Tuple8 = ("apple", "banana", "cherry", "Automation Testing", "Credence is Best", 1, True)
print(Tuple1)
print(Tuple2)
print(Tuple3)
print(Tuple4)
print(Tuple5)
print(Tuple6)
print(Tuple7)
print(Tuple8)
print(Tuple1+Tuple6)
print(Tuple4*3)
print(3 in Tuple7)
print(len(Tuple8))
print(max(Tuple5))
print(min(Tuple1))
print(Tuple1.count(4))
print(Tuple5.index(3))
Tuple11 = (1, 2, 3, 4, 5)
List1 = list(Tuple1)
print("Convert Tuple to List : ", List1)
list2=list(Tuple8)
print(list2)
print("\n 05. Convert Tuple to String : ")
Tuple1 = (1, 2, 3, 4, 5)
print("Tuple to String : ", str(Tuple1))